# Generated by Django 3.2.5 on 2022-10-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoIdentificacion', models.CharField(choices=[('CE', 'CEDULA'), ('RU', 'RUC'), ('PA', 'PASAPORTE')], default='CE', max_length=2)),
                ('dui', models.BigIntegerField(help_text='La cedula debe tener 10 digitos')),
                ('nombres', models.TextField(max_length=50)),
                ('apellidos', models.TextField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
            options={
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.BigIntegerField(default=0, unique=True)),
                ('razonSocial', models.TextField(max_length=50, unique=True)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['razonSocial'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Ingrese el Tipo de producto', max_length=50)),
                ('fechaRegistroTipoProducto', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dui', models.BigIntegerField(help_text='La cedula debe tener 10 digitos')),
                ('nombres', models.TextField(max_length=50)),
                ('apellidos', models.TextField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Ingrese la descripcion del producto', max_length=50)),
                ('cantidad', models.IntegerField(default=0, editable=False)),
                ('fechaRegistroProducto', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbodega.tipoproducto')),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenEgreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroOrdenEgreso', models.IntegerField(unique=True)),
                ('fechaEgreso', models.DateTimeField(auto_now=True)),
                ('valorTotal', models.DecimalField(decimal_places=5, max_digits=5)),
                ('fechaRegistroOrdenEgreso', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroOrdenCompra', models.IntegerField(unique=True)),
                ('fechaCompra', models.DateTimeField(auto_now=True)),
                ('valorTotal', models.DecimalField(decimal_places=5, max_digits=5)),
                ('fechaRegistroOrdenCompra', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.proveedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroLote', models.TextField(help_text='Ingrese el numero de lote del producto')),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fechaCaducidad', models.DateField(blank=True, default='', null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenEgreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=5, max_digits=5)),
                ('valorTotalItem', models.DecimalField(decimal_places=5, max_digits=5)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.loteproducto')),
                ('ordenCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.ordencompra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=5, max_digits=5)),
                ('valorTotalItem', models.DecimalField(decimal_places=5, max_digits=5)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.loteproducto')),
                ('ordenCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.ordencompra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.producto')),
            ],
        ),
    ]
