# Generated by Django 3.2.5 on 2022-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0005_alter_ordencompra_fechacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordencompra',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemordencompra',
            name='valorTotalItem',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemordenegreso',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemordenegreso',
            name='valorTotalItem',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='valorTotal',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenegreso',
            name='valorTotal',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
