# Generated by Django 3.2.5 on 2022-11-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0010_auto_20221110_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordencompra',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemordencompra',
            name='ordenCompra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbodega.ordencompra'),
        ),
        migrations.AddField(
            model_name='itemordencompra',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemordencompra',
            name='valorTotalItem',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
