# Generated by Django 3.2.5 on 2022-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0011_auto_20221110_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='numeroOrdenCompra',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
