# Generated by Django 3.2.5 on 2022-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0013_alter_ordenegreso_numeroordenegreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproducto',
            name='fechaCaducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
