# Generated by Django 3.2.5 on 2022-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0002_auto_20221029_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenegreso',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
