# Generated by Django 3.2.5 on 2022-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0003_auto_20221029_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaCompra',
            field=models.DateTimeField(),
        ),
    ]
