# Generated by Django 3.2.5 on 2022-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0004_alter_ordencompra_fechacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaCompra',
            field=models.DateField(),
        ),
    ]
