# Generated by Django 3.2.5 on 2022-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0006_auto_20221031_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordencompra',
            name='lote',
            field=models.TextField(help_text='Ingrese el numero de lote del producto'),
        ),
    ]
