# Generated by Django 3.2.5 on 2022-11-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0007_alter_itemordencompra_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
