# Generated by Django 3.2.5 on 2022-11-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0008_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
