# Generated by Django 3.2.5 on 2022-11-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbodega', '0009_cliente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordencompra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='itemordencompra',
            name='ordenCompra',
        ),
        migrations.RemoveField(
            model_name='itemordencompra',
            name='precioUnitario',
        ),
        migrations.RemoveField(
            model_name='itemordencompra',
            name='valorTotalItem',
        ),
    ]
